/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface MainContract extends Truffle.Contract<MainInstance> {
  "new"(
    _fsocietyAddress: string,
    _tokenFactoryAddress: string,
    _poolFactoryAddress: string,
    meta?: Truffle.TransactionDetails
  ): Promise<MainInstance>;
}

type AllEvents = never;

export interface MainInstance extends Truffle.ContractInstance {
  methods: {};

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
