/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type TokenCreated = ContractEventLog<{
  token: string;
  name: string;
  symbol: string;
  0: string;
  1: string;
  2: string;
}>;

export interface ProjectTokenFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ProjectTokenFactory;
  clone(): ProjectTokenFactory;
  methods: {
    createToken(
      _name: string,
      _symbol: string,
      _totalSupply: number | string | BN,
      _ammGlobalShare: number | string | BN,
      _ammPoolShare: number | string | BN,
      _authorGlobalShare: number | string | BN,
      _authorPoolShare: number | string | BN,
      _amm: string,
      _author: string
    ): NonPayableTransactionObject<string>;
  };
  events: {
    TokenCreated(cb?: Callback<TokenCreated>): EventEmitter;
    TokenCreated(
      options?: EventOptions,
      cb?: Callback<TokenCreated>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "TokenCreated", cb: Callback<TokenCreated>): void;
  once(
    event: "TokenCreated",
    options: EventOptions,
    cb: Callback<TokenCreated>
  ): void;
}
