/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc20PermitSol from "./draft-IERC20Permit.sol";
export type { draftIerc20PermitSol };
export type { ERC20Wrapper } from "./ERC20Wrapper";
export type { IERC20Metadata } from "./IERC20Metadata";
