/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ProjectTokenFactoryContract
  extends Truffle.Contract<ProjectTokenFactoryInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<ProjectTokenFactoryInstance>;
}

export interface TokenCreated {
  name: "TokenCreated";
  args: {
    token: string;
    name: string;
    symbol: string;
    0: string;
    1: string;
    2: string;
  };
}

type AllEvents = TokenCreated;

export interface ProjectTokenFactoryInstance extends Truffle.ContractInstance {
  createToken: {
    (
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    sendTransaction(
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    createToken: {
      (
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      sendTransaction(
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
