/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../../../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IProjectTokenFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IProjectTokenFactory;
  clone(): IProjectTokenFactory;
  methods: {
    createToken(
      _name: string,
      _symbol: string,
      _totalSupply: number | string | BN,
      _ammShare: number | string | BN,
      _authorShare: number | string | BN,
      _amm: string,
      _author: string
    ): NonPayableTransactionObject<string>;

    tokens(tokenAddress: string): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
