/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { InitializableContract } from "./Initializable";
import { ERC20UpgradeableContract } from "./ERC20Upgradeable";
import { IERC20MetadataUpgradeableContract } from "./IERC20MetadataUpgradeable";
import { IERC20UpgradeableContract } from "./IERC20Upgradeable";
import { ContextUpgradeableContract } from "./ContextUpgradeable";
import { OwnableContract } from "./Ownable";
import { ERC20Contract } from "./ERC20";
import { IERC20PermitContract } from "./IERC20Permit";
import { ERC20WrapperContract } from "./ERC20Wrapper";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC20Contract } from "./IERC20";
import { AMMContract } from "./AMM";
import { WETHTokenContract } from "./WETHToken";
import { IWETHContract } from "./IWETH";
import { IPoolFactoryContract } from "./IPoolFactory";
import { LPTokenERC20Contract } from "./LPTokenERC20";
import { PoolContract } from "./Pool";
import { PoolFactoryContract } from "./PoolFactory";
import { ProjectsContract } from "./Projects";
import { IProjectTokenERC20Contract } from "./IProjectTokenERC20";
import { IProjectTokenFactoryContract } from "./IProjectTokenFactory";
import { ProjectTokenERC20Contract } from "./ProjectTokenERC20";
import { ProjectTokenFactoryContract } from "./ProjectTokenFactory";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Initializable"): InitializableContract;
      require(name: "ERC20Upgradeable"): ERC20UpgradeableContract;
      require(
        name: "IERC20MetadataUpgradeable"
      ): IERC20MetadataUpgradeableContract;
      require(name: "IERC20Upgradeable"): IERC20UpgradeableContract;
      require(name: "ContextUpgradeable"): ContextUpgradeableContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IERC20Permit"): IERC20PermitContract;
      require(name: "ERC20Wrapper"): ERC20WrapperContract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "AMM"): AMMContract;
      require(name: "WETHToken"): WETHTokenContract;
      require(name: "IWETH"): IWETHContract;
      require(name: "IPoolFactory"): IPoolFactoryContract;
      require(name: "LPTokenERC20"): LPTokenERC20Contract;
      require(name: "Pool"): PoolContract;
      require(name: "PoolFactory"): PoolFactoryContract;
      require(name: "Projects"): ProjectsContract;
      require(name: "IProjectTokenERC20"): IProjectTokenERC20Contract;
      require(name: "IProjectTokenFactory"): IProjectTokenFactoryContract;
      require(name: "ProjectTokenERC20"): ProjectTokenERC20Contract;
      require(name: "ProjectTokenFactory"): ProjectTokenFactoryContract;
    }
  }
}

export { InitializableContract, InitializableInstance } from "./Initializable";
export {
  ERC20UpgradeableContract,
  ERC20UpgradeableInstance,
} from "./ERC20Upgradeable";
export {
  IERC20MetadataUpgradeableContract,
  IERC20MetadataUpgradeableInstance,
} from "./IERC20MetadataUpgradeable";
export {
  IERC20UpgradeableContract,
  IERC20UpgradeableInstance,
} from "./IERC20Upgradeable";
export {
  ContextUpgradeableContract,
  ContextUpgradeableInstance,
} from "./ContextUpgradeable";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { IERC20PermitContract, IERC20PermitInstance } from "./IERC20Permit";
export { ERC20WrapperContract, ERC20WrapperInstance } from "./ERC20Wrapper";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { AMMContract, AMMInstance } from "./AMM";
export { WETHTokenContract, WETHTokenInstance } from "./WETHToken";
export { IWETHContract, IWETHInstance } from "./IWETH";
export { IPoolFactoryContract, IPoolFactoryInstance } from "./IPoolFactory";
export { LPTokenERC20Contract, LPTokenERC20Instance } from "./LPTokenERC20";
export { PoolContract, PoolInstance } from "./Pool";
export { PoolFactoryContract, PoolFactoryInstance } from "./PoolFactory";
export { ProjectsContract, ProjectsInstance } from "./Projects";
export {
  IProjectTokenERC20Contract,
  IProjectTokenERC20Instance,
} from "./IProjectTokenERC20";
export {
  IProjectTokenFactoryContract,
  IProjectTokenFactoryInstance,
} from "./IProjectTokenFactory";
export {
  ProjectTokenERC20Contract,
  ProjectTokenERC20Instance,
} from "./ProjectTokenERC20";
export {
  ProjectTokenFactoryContract,
  ProjectTokenFactoryInstance,
} from "./ProjectTokenFactory";
