/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IProjectTokenFactoryContract
  extends Truffle.Contract<IProjectTokenFactoryInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IProjectTokenFactoryInstance>;
}

type AllEvents = never;

export interface IProjectTokenFactoryInstance extends Truffle.ContractInstance {
  createToken: {
    (
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    sendTransaction(
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _name: string,
      _symbol: string,
      _totalSupply: number | BN | string,
      _ammGlobalShare: number | BN | string,
      _ammPoolShare: number | BN | string,
      _authorGlobalShare: number | BN | string,
      _authorPoolShare: number | BN | string,
      _amm: string,
      _author: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    createToken: {
      (
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      sendTransaction(
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _name: string,
        _symbol: string,
        _totalSupply: number | BN | string,
        _ammGlobalShare: number | BN | string,
        _ammPoolShare: number | BN | string,
        _authorGlobalShare: number | BN | string,
        _authorPoolShare: number | BN | string,
        _amm: string,
        _author: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
